- name: Run Billing Script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: python get_cost.py

    - name: Upload CSV as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: daily-cost-report
        path: ./*.csv        # เพิ่ม ./ เข้าไปข้างหน้าเพื่อให้หาไฟล์ที่ Root directory
        if-no-files-found: error # ถ้าหาไม่เจอ ให้สั่ง Error ทันทีเพื่อแจ้งเรา